# Generated by Django 3.2.2 on 2021-05-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210518_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner',
        ),
    ]
